/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.texera.amber.engine.architecture.controller

import org.apache.texera.amber.core.storage.VFSURIFactory
import org.apache.texera.amber.core.virtualidentity.PhysicalOpIdentity
import org.apache.texera.amber.core.workflow.{
  CachedOutput,
  GlobalPortIdentity,
  PhysicalLink,
  PhysicalPlan,
  WorkflowContext,
  WorkflowSettings
}
import org.apache.texera.amber.engine.architecture.scheduling.config.{OutputPortConfig, ResourceConfig}
import org.apache.texera.amber.engine.architecture.scheduling.{
  PreSchedulingHints,
  Region,
  RegionIdentity
}
import org.apache.texera.amber.util.serde.GlobalPortIdentitySerde
import org.jgrapht.Graph
import org.jgrapht.alg.connectivity.BiconnectivityInspector

import java.net.URI
import scala.collection.mutable
import scala.jdk.CollectionConverters._

/**
  * Pre-scheduling cache step for forced-cache-reuse MVP semantics.
  *
  * This step runs before CostBasedScheduleGenerator and only prepares planning inputs:
  * residual planning plan, workflow settings override, precomputed URI/config hints, and leading
  * skipped regions. The final schedule is still generated by CostBasedScheduleGenerator.
  */
object CacheReusePreSchedulingStep {

  /**
    * Output of the pre-scheduling phase consumed by CostBasedScheduleGenerator.
    */
  case class CacheReusePreSchedulingResult(
      planningPhysicalPlan: PhysicalPlan,
      planningWorkflowSettings: WorkflowSettings,
      planningHints: PreSchedulingHints,
      leadingRegions: Set[Region]
  )

  /**
    * Deterministic requiredness result under forced-cache semantics.
    */
  private case class RequirednessAnalysis(
      requiredSeedPorts: Set[GlobalPortIdentity],
      executeOperators: Set[PhysicalOpIdentity],
      freshRequiredOutputPorts: Set[GlobalPortIdentity],
      cacheHitRequiredOutputPorts: Set[GlobalPortIdentity],
      freshRequiredLinks: Set[PhysicalLink],
      cacheFedLinks: Set[PhysicalLink]
  )

  /**
    * Prepare cache-aware planning inputs for CostBasedScheduleGenerator.
    */
  def prepare(
      workflowContext: WorkflowContext,
      physicalPlan: PhysicalPlan
  ): CacheReusePreSchedulingResult = {
    val cachedOutputsByPort = workflowContext.workflowSettings.cachedOutputs.map {
      case (serializedId, cachedOutput) =>
        GlobalPortIdentitySerde.deserializeFromString(serializedId) -> cachedOutput
    }

    if (cachedOutputsByPort.isEmpty) {
      return CacheReusePreSchedulingResult(
        planningPhysicalPlan = physicalPlan,
        planningWorkflowSettings = workflowContext.workflowSettings,
        planningHints = PreSchedulingHints(),
        leadingRegions = Set.empty
      )
    }

    val analysis = analyzeRequiredness(physicalPlan, workflowContext, cachedOutputsByPort)
    val skipRegions = buildSkipRegions(physicalPlan, analysis, cachedOutputsByPort)
    val residualPlan =
      buildResidualPlan(physicalPlan, analysis.executeOperators, analysis.freshRequiredLinks)
    val planningWorkflowSettings = workflowContext.workflowSettings.copy(
      outputPortsNeedingStorage =
        analysis.requiredSeedPorts.intersect(analysis.freshRequiredOutputPorts)
    )
    val planningHints = buildPlanningHints(residualPlan, analysis, cachedOutputsByPort)

    CacheReusePreSchedulingResult(
      planningPhysicalPlan = residualPlan,
      planningWorkflowSettings = planningWorkflowSettings,
      planningHints = planningHints,
      leadingRegions = skipRegions
    )
  }

  /**
    * Backward requiredness propagation with forced cache reuse:
    * - cache hit required outputs do not force execution,
    * - cache miss required outputs force execution and upstream propagation.
    */
  private def analyzeRequiredness(
      plan: PhysicalPlan,
      workflowContext: WorkflowContext,
      cachedOutputsByPort: Map[GlobalPortIdentity, CachedOutput]
  ): RequirednessAnalysis = {
    val requiredSeeds =
      workflowContext.workflowSettings.outputPortsNeedingStorage
        .filter(pid => plan.operators.exists(_.id == pid.opId))

    val requiredOutputPorts = mutable.Set[GlobalPortIdentity]()
    requiredOutputPorts ++= requiredSeeds
    val executeOperators = mutable.Set[PhysicalOpIdentity]()

    var changed = true
    while (changed) {
      changed = false
      plan.topologicalIterator().foreach { opId =>
        val op = plan.getOperator(opId)
        val requiredOutputsOfOp =
          op.outputPorts.keys
            .map(portId => GlobalPortIdentity(op.id, portId))
            .filter(requiredOutputPorts.contains)
            .toSet
        if (requiredOutputsOfOp.nonEmpty) {
          val hasCacheMiss = requiredOutputsOfOp.exists(pid => !cachedOutputsByPort.contains(pid))
          if (hasCacheMiss) {
            if (!executeOperators.contains(opId)) {
              executeOperators += opId
              changed = true
            }
            plan.getUpstreamPhysicalLinks(opId).foreach { link =>
              val upstreamOutput = GlobalPortIdentity(link.fromOpId, link.fromPortId)
              if (!requiredOutputPorts.contains(upstreamOutput)) {
                requiredOutputPorts += upstreamOutput
                changed = true
              }
            }
          }
        }
      }
    }

    val freshRequiredOutputPorts =
      requiredOutputPorts.filter(pid => !cachedOutputsByPort.contains(pid)).toSet
    val cacheHitRequiredOutputPorts =
      requiredOutputPorts.filter(cachedOutputsByPort.contains).toSet

    val linksIntoExecute = plan.links.filter(link => executeOperators.contains(link.toOpId))
    val freshRequiredLinks = linksIntoExecute
      .filter(link =>
        freshRequiredOutputPorts.contains(GlobalPortIdentity(link.fromOpId, link.fromPortId))
      )
      .toSet
    val cacheFedLinks = linksIntoExecute
      .filter(link =>
        cacheHitRequiredOutputPorts.contains(GlobalPortIdentity(link.fromOpId, link.fromPortId))
      )
      .toSet

    RequirednessAnalysis(
      requiredSeedPorts = requiredSeeds,
      executeOperators = executeOperators.toSet,
      freshRequiredOutputPorts = freshRequiredOutputPorts,
      cacheHitRequiredOutputPorts = cacheHitRequiredOutputPorts,
      freshRequiredLinks = freshRequiredLinks,
      cacheFedLinks = cacheFedLinks
    )
  }

  /**
    * Keep only execute operators and fresh-required dependencies.
    */
  private def buildResidualPlan(
      plan: PhysicalPlan,
      executeOperators: Set[PhysicalOpIdentity],
      freshRequiredLinks: Set[PhysicalLink]
  ): PhysicalPlan = {
    val linksToRemove = plan.links.diff(freshRequiredLinks)
    val linksPrunedPlan = linksToRemove.foldLeft(plan)((acc, link) => acc.removeLink(link))
    linksPrunedPlan.getSubPlan(executeOperators)
  }

  /**
    * Cache entries persist the `/result` leaf URI, but scheduling port configs and the input-port
    * materialization readers expect the port *base* URI: they derive `resultURI`/`stateURI` from it
    * via `VFSURIFactory`. Reconstruct the base from a cached `/result` URI so reuse-only ports line
    * up with the (post state-materialization) base/result/state storage layout.
    */
  private def portBaseURIOf(cachedResultUri: URI): URI = {
    val (workflowId, executionId, globalPortIdOpt, _) = VFSURIFactory.decodeURI(cachedResultUri)
    val globalPortId = globalPortIdOpt.getOrElse(
      throw new IllegalArgumentException(
        s"Cached result URI is missing a globalPortId: $cachedResultUri"
      )
    )
    VFSURIFactory.createPortBaseURI(workflowId, executionId, globalPortId)
  }

  /**
    * Prepare generic planning hints for CostBasedScheduleGenerator.
    */
  private def buildPlanningHints(
      residualPlan: PhysicalPlan,
      analysis: RequirednessAnalysis,
      cachedOutputsByPort: Map[GlobalPortIdentity, CachedOutput]
  ): PreSchedulingHints = {
    val residualOps = residualPlan.operators.map(_.id).toSet

    val outputPortConfigOverrides = analysis.cacheHitRequiredOutputPorts
      .filter(pid => residualOps.contains(pid.opId))
      .flatMap { pid =>
        cachedOutputsByPort.get(pid).map { cached =>
          pid -> OutputPortConfig(
            storageURIBase = portBaseURIOf(cached.resultUri),
            cachedTupleCount = cached.tupleCount,
            materialize = false
          )
        }
      }
      .toMap

    val inputPortUriOverrides = analysis.cacheFedLinks
      .filter(link => residualOps.contains(link.toOpId))
      .foldLeft(Map.empty[GlobalPortIdentity, List[URI]]) {
        case (acc, link) =>
          val inputPort = GlobalPortIdentity(link.toOpId, link.toPortId, input = true)
          val outputPort = GlobalPortIdentity(link.fromOpId, link.fromPortId)
          cachedOutputsByPort.get(outputPort) match {
            case Some(cached) =>
              val uris = acc.getOrElse(inputPort, List.empty) :+ portBaseURIOf(cached.resultUri)
              acc.updated(inputPort, uris)
            case None =>
              acc
          }
      }

    PreSchedulingHints(outputPortConfigOverrides, inputPortUriOverrides)
  }

  /**
    * Build skipped regions (outside Pasta scope) with reuse-only output-port bindings.
    */
  private def buildSkipRegions(
      plan: PhysicalPlan,
      analysis: RequirednessAnalysis,
      cachedOutputsByPort: Map[GlobalPortIdentity, CachedOutput]
  ): Set[Region] = {
    val skipOperators = plan.operators.map(_.id).diff(analysis.executeOperators)
    if (skipOperators.isEmpty) {
      return Set.empty
    }

    val skipInternalLinks = plan.links
      .filter(link => skipOperators.contains(link.fromOpId) && skipOperators.contains(link.toOpId))
    val linksToRemove = plan.links.diff(skipInternalLinks)
    val linksPrunedPlan = linksToRemove.foldLeft(plan)((acc, link) => acc.removeLink(link))
    val skipPlan = linksPrunedPlan.getSubPlan(skipOperators)

    createConnectedRegions(skipPlan).map { region =>
      val reuseOnlyOutputConfigs = analysis.cacheHitRequiredOutputPorts
        .filter(pid => region.physicalOps.exists(_.id == pid.opId))
        .flatMap { outputPort =>
          cachedOutputsByPort.get(outputPort).map { cached =>
            outputPort -> OutputPortConfig(
              storageURIBase = portBaseURIOf(cached.resultUri),
              cachedTupleCount = cached.tupleCount,
              materialize = false
            )
          }
        }
        .toMap
      region.copy(
        cached = true,
        resourceConfig = Some(ResourceConfig(portConfigs = reuseOnlyOutputConfigs))
      )
    }
  }

  /**
    * Region skeleton partitioning without materialized-edge cuts.
    */
  private def createConnectedRegions(plan: PhysicalPlan): Set[Region] = {
    val connectedComponents: Set[Graph[PhysicalOpIdentity, PhysicalLink]] =
      new BiconnectivityInspector[PhysicalOpIdentity, PhysicalLink](
        plan.dag
      ).getConnectedComponents.asScala.toSet

    connectedComponents.zipWithIndex.map {
      case (connectedSubDAG, idx) =>
        val operators: Set[PhysicalOpIdentity] = connectedSubDAG.vertexSet().asScala.toSet
        val links: Set[PhysicalLink] = operators
          .flatMap(opId => plan.getUpstreamPhysicalLinks(opId) ++ plan.getDownstreamPhysicalLinks(opId))
          .filter(link => operators.contains(link.fromOpId))
        val physicalOps = operators.map(plan.getOperator)
        val ports: Set[GlobalPortIdentity] = physicalOps.flatMap { op =>
          op.inputPorts.keys
            .map(inputPortId => GlobalPortIdentity(op.id, inputPortId, input = true))
            .toSet ++
            op.outputPorts.keys.map(outputPortId => GlobalPortIdentity(op.id, outputPortId)).toSet
        }
        Region(
          id = RegionIdentity(idx.toLong),
          physicalOps = physicalOps,
          physicalLinks = links,
          ports = ports,
          resourceConfig = None,
          cached = true
        )
    }
  }

}
